spring:
  liquibase:
    change-log: classpath:/db.changelog/changelogs/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/portfoliodb
    user: portfolio_user
    password: portfolio_pass
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      max-lifetime: 1800000
    url: jdbc:postgresql://localhost:5432/portfoliodb
    username: portfolio_user
    password: portfolio_pass
    driver-class-name: org.postgresql.Driver